# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: bezos-api

frameworkVersion: '3'

# The `provider` block defines where your service will be deployed
provider:
  # name: ${opt:stage}-hello
  name: aws
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  runtime: nodejs16.x
  # Default memory size for functions (default: 1024MB)
  memorySize: 512
  # Default timeout for functions (default: 6 seconds)
  # Note: API Gateway has a maximum timeout of 30 seconds
  timeout: 20 # seconds
  # Duration for CloudWatch log retention (default: forever)
  logRetentionInDays: 14
  deploymentMethod: direct
  # Add custom environment variables:
  # environment:
  #     REDIS_ENDPOINT: ${env:REDIS_ENDPOINT}
  #     REDIS_PORT: ${env:REDIS_PORT}
  #     REDIS_PASSWORD: ${env:REDIS_PASSWORD}
  #     CONTRIBUTION_STORE_REPO: ${env:CONTRIBUTION_STORE_REPO}
  
# The `functions` block defines what code to deploy
functions:
  generateQuote:
    handler: handler.generateQuote
    # The `events` block defines how to trigger the handler.generateQuote code
    # Modifies the URL => endpoint: GET - https://jlt5srv171.execute-api.us-east-1.amazonaws.com/dev/hello-world
    events:
      - http:
          path: /api/random
          method: get
          cors: true
    environment:
      URL: { "Fn::Join" : ["", [" https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.region}/path/to/resource" ] ]  }

