name: 🚀 Deploy Lambda

# Continuous Deployment for AWS Lambda
# https://github.com/marketplace/actions/aws-lambda-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lambda/**

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    environment:
      name: bezos-api
      url: ${{ steps.aws-deploy.outputs.api_url }}

    steps:
      - uses: actions/checkout@v3

      - name: ➕ Setup serverless package
        # Authenticate with AWS credentials
        run: |
          npm install -g serverless@3.22.0
          serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      # https://github.com/bahmutov/npm-install
      # GitHub Action for install npm dependencies with caching without any configuration
      - name: "📦 Install Dependencies"
        uses: bahmutov/npm-install@v1

      - name: 🚀 Deploy Lambda function
        id: aws-deploy
        # 1) Export environment variables here before deployment:
        # export MY_ENV_VAR=${{ secrets.MY_ENV_VAR }};
        # 2) Run the deployment command:
        # serverless deploy function --function myFunction
        # 3) Outputs the API_URL to "deploy.out" file
        # 4) Sets the step output value, so environment can access the url
        run: |
          serverless deploy --stage prod --region us-east-1
          echo "::set-output name=api_url::$(cat deploy.out)"